In [26]:
import tensorflow as tf
import numpy as np

In [27]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

with tf.Session() as sess:
    a = tf.placeholder(tf.float32, [None, 3])
    b = tf.nn.l2_normalize(a)
    output = sess.run(b, {a: arr})

print(output)
print(output.shape)

[[0.05923489 0.11846977 0.17770466]
 [0.23693955 0.29617444 0.35540932]
 [0.4146442  0.4738791  0.53311396]]
(3, 3)
